[package]
name = "egui_code_editor"
version = "0.1.2"
edition = "2021"
license = "MIT"
repository = "https://github.com/p4ymak/egui_code_editor"
description = "egui code editor widget with numbered lines and syntax highlighting.."
readme = "README.md"
keywords = ["egui", "GUI", "code", "editor", "syntax", "highlighting"]

[dependencies]
egui = "0.22.0"
syntect = { version = "5.0.0", optional = true }

[features]
default = []
syntect = ["dep:syntect"]

